# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-07 16:05
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('emp_id', models.CharField(max_length=20, verbose_name='员工编号')),
                ('emp_name', models.CharField(max_length=20, verbose_name='员工姓名')),
                ('primission', models.CharField(max_length=50, verbose_name='所有权限')),
                ('phone', models.CharField(max_length=30, verbose_name='电话')),
            ],
            options={
                'verbose_name': '员工信息',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BanChengP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.CharField(max_length=20, unique=True, verbose_name='半成品编号')),
                ('b_name', models.CharField(max_length=30, verbose_name='半成品名称')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('m_id', models.CharField(max_length=255, verbose_name='毛坯id')),
            ],
            options={
                'verbose_name': '半成品仓库信息',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='客户名称')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '客户信息',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='所属部门id')),
                ('name', models.CharField(max_length=30, verbose_name='部门名字')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '部门信息',
            },
        ),
        migrations.CreateModel(
            name='DingDanlcsj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_date', models.DateField(verbose_name='到达当前部门的时间')),
                ('dep_count', models.IntegerField(verbose_name='到哪数量')),
                ('is_valid', models.BooleanField(default=True)),
                ('departmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj01.Department', verbose_name='到达部门的id')),
            ],
            options={
                'verbose_name': '订单流程时间信息',
            },
        ),
        migrations.CreateModel(
            name='GongYluXian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proc_name', models.CharField(max_length=255)),
                ('dep_id', models.CharField(max_length=50)),
                ('is_valid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Maopi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.CharField(max_length=100, unique=True, verbose_name='毛坯编号')),
                ('m_name', models.CharField(max_length=30, verbose_name='毛坯名称')),
                ('count', models.IntegerField(verbose_name='货存数量')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('b_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '毛坯仓库信息',
            },
        ),
        migrations.CreateModel(
            name='order_pruduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banchengp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj01.BanChengP', to_field='b_id')),
                ('gongyluxian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj01.GongYluXian')),
                ('maopi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj01.Maopi', to_field='m_id')),
            ],
            options={
                'verbose_name': '订单产品',
            },
        ),
        migrations.CreateModel(
            name='Sales_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30, unique=True, verbose_name='订单编号')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('phase', models.IntegerField(verbose_name='预计生产周期')),
                ('is_done', models.BooleanField(default=False, verbose_name='订单是否完成')),
                ('si_stop', models.BooleanField(default=False, verbose_name='暂停订单')),
                ('quantity', models.IntegerField(verbose_name='订单数量')),
                ('f_data', models.DateTimeField(verbose_name='完成日期')),
                ('s_data', models.DateTimeField(auto_now_add=True, verbose_name='下单日期')),
                ('process_id', models.CharField(max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj01.Customer', verbose_name='客户id')),
                ('user_id', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='员工id')),
            ],
            options={
                'verbose_name': '订单销售信息',
            },
        ),
        migrations.AddField(
            model_name='order_pruduct',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj01.Sales_order', to_field='order_id'),
        ),
        migrations.AddField(
            model_name='dingdanlcsj',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj01.Sales_order', verbose_name='订单编号'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj01.Department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
