# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-10 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pj01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='user_id',
        ),
    ]
