# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-10 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj01', '0002_remove_department_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maopi',
            name='b_id',
        ),
        migrations.AddField(
            model_name='maopi',
            name='banchengpin',
            field=models.ManyToManyField(to='pj01.BanChengP'),
        ),
    ]
